[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Permissions-Policy = "interest-cohort=()"
    Content-Security-Policy = '''
    default-src 'none';
    base-uri 'self';
    script-src 'self';
    style-src 'self';
    font-src 'self';
    form-action 'self';
    connect-src 'self' https://ren-phrase-dict.netlify.app;
    img-src 'self' data:;
    '''

[[redirects]]
  from = "/dict/*"
  to = "https://ren-phrase-dict.netlify.app/dict/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
