# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: yarn
    - name: Install deps
      run: yarn install --immutable
    - name: Build
      run: yarn run build
    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: gh-deploy
        server: ${{ secrets.SSH_DEPLOY_HOST }}
        port: ${{ secrets.SSH_DEPLOY_PORT }}
        local_path: ./dist/*
        remote_path: /xkcdpw/app/
        password: ${{ secrets.SSH_DEPLOY_PW }}
        sftp_only: true
        # delete_remote_files: true

